### PR TITLE
Update versions & APK to ZIP

### PR DESCRIPTION
**Pull request by Kyza**

### CODE REVIEW

**Comment by AAGaming00** [comment]
Forgot the settings.gradle and gradle.properties changes

**Comment by Kyza** [comment]
> Forgot the settings.gradle and gradle.properties changes

Don't know what's supposed to be changed there.

**Comment by AAGaming00** [comment]
look at [this](https://github.com/Vendicated/AliucordPlugins/commit/2dcf85f8db90922d15ab6f9491b5134b7d63c460)

**Comment by AAGaming00** [comment]
epic fix

**Pull request merged**
